// Irodori-TTS の絵文字注釈。原典は
// https://huggingface.co/Aratako/Irodori-TTS-v4.1-Small/raw/main/EMOJI_ANNOTATIONS.md
// 実行時に取りに行かないよう取り込んである。並びは原典のまま（意味のまとまりではなく
// 原典の順序を保つことで、原典と突き合わせて確かめられる）。
export type EmojiAnnotation = { emoji: string; ja: string; en: string }

export const EMOJI_ANNOTATIONS: readonly EmojiAnnotation[] = [
  { emoji: '👂', ja: '囁き、耳元の音', en: 'Whisper, sounds close to the ear' },
  { emoji: '😮‍💨', ja: '吐息、溜息、寝息', en: 'Breath, sigh, sleeping breath' },
  { emoji: '⏸️', ja: '間、沈黙', en: 'Pause, silence' },
  { emoji: '🤭', ja: '笑い（くすくす、含み笑いなど）', en: 'Chuckle, giggle, suppressed laugh' },
  { emoji: '🥵', ja: '喘ぎ、うめき声、唸り声', en: 'Panting, moan, groan' },
  { emoji: '📢', ja: 'エコー、リバーブ', en: 'Echo, reverb' },
  { emoji: '😏', ja: 'からかうように、甘えるように', en: 'Teasing, playfully sweet / coaxing' },
  {
    emoji: '🥺',
    ja: '声を震わせながら、自信のなさげに',
    en: 'Trembling voice, timidly / uncertainly',
  },
  { emoji: '🌬️', ja: '息切れ、荒い息遣い、呼吸音', en: 'Shortness of breath, heavy breathing' },
  { emoji: '😮', ja: '息をのむ', en: 'Gasp' },
  { emoji: '👅', ja: '舐める音、咀嚼音、水音', en: 'Licking sound, chewing sound, wet sound' },
  { emoji: '💋', ja: 'リップノイズ', en: 'Lip smack / lip noise' },
  { emoji: '🫶', ja: '優しく', en: 'Gently, tenderly' },
  { emoji: '😭', ja: '嗚咽、泣き声、悲しみ', en: 'Sobbing, crying, sorrowfully / sadly' },
  { emoji: '😱', ja: '悲鳴、叫び、絶叫', en: 'Scream, shout, shriek' },
  { emoji: '😪', ja: '眠そうに、気だるげに', en: 'Sleepily, sluggishly / languidly' },
  { emoji: '😴', ja: '寝言、いびき', en: 'Sleep talking, snoring' },
  {
    emoji: '⏩',
    ja: '早口、一気にまくしたてる、急いで',
    en: 'Fast-speaking, rapid-fire, hurriedly',
  },
  {
    emoji: '📞',
    ja: '電話越し、スピーカー越しのような音',
    en: 'Over the phone, through a speaker',
  },
  { emoji: '🐢', ja: 'ゆっくりと', en: 'Slowly' },
  { emoji: '🥤', ja: '唾を飲み込む音', en: 'Gulp, swallowing sound' },
  {
    emoji: '🤧',
    ja: '咳き込み、鼻をすする、くしゃみ、咳払い',
    en: 'Coughing, sniffling, sneeze, clearing throat',
  },
  { emoji: '😒', ja: '舌打ち', en: 'Tutting, clicking tongue' },
  { emoji: '😰', ja: '慌てて、動揺、緊張、どもり', en: 'Panicked, agitated, nervous, stuttering' },
  { emoji: '😆', ja: '喜びながら', en: 'Joyfully, happily' },
  { emoji: '💥', ja: '勢いよく、勢いに任せて', en: 'With force / momentum, forcefully' },
  { emoji: '😠', ja: '怒り、不満げに、拗ねながら', en: 'Angry, displeased, sulking' },
  { emoji: '😲', ja: '驚き、感嘆', en: 'Surprise, awe / exclamation' },
  { emoji: '🥱', ja: 'あくび', en: 'Yawn' },
  { emoji: '😖', ja: '苦しげに', en: 'Painfully, agonizingly' },
  { emoji: '😟', ja: '心配そうに', en: 'Anxiously, worriedly' },
  { emoji: '🫣', ja: '恥ずかしそうに、照れながら', en: 'Shyly, bashfully' },
  { emoji: '🙄', ja: '呆れたように', en: 'Exasperatedly, rolling eyes' },
  { emoji: '😊', ja: '楽しげに、嬉しそうに', en: 'Cheerfully, gladly' },
  { emoji: '😎', ja: '得意げに、自信ありげに', en: 'Confidently, proudly' },
  { emoji: '👌', ja: '相槌、頷く音', en: 'Backchanneling, sound of agreement' },
  { emoji: '🙏', ja: '懇願するように', en: 'Pleadingly, begging' },
  { emoji: '🥴', ja: '酔っ払って', en: 'Drunkenly' },
  { emoji: '🎵', ja: '鼻歌', en: 'Humming' },
  { emoji: '🤐', ja: '口を塞がれて', en: 'Muffled (mouth covered)' },
  { emoji: '😌', ja: '安堵、満足げに', en: 'Relieved, contentedly' },
  { emoji: '🤔', ja: '疑問の声', en: 'Questioning voice, wondering' },
  { emoji: '💪', ja: '力を込めて、力強く', en: 'With effort, strongly' },
  { emoji: '👃', ja: '匂いを嗅ぐ音', en: 'Sniffing / smelling sound' },
  { emoji: '📖', ja: 'ナレーション、独白、モノローグ', en: 'Narration, monologue' },
]
